# Generated by Django 6.0.3 on 2026-03-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.FloatField()),
                ('prix_promotion', models.FloatField(default=0)),
                ('pourcentage_promotion', models.FloatField(default=0)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('nombre_vendus', models.IntegerField(default=0)),
                ('commentaires', models.CharField(blank=True, max_length=255)),
                ('categorie', models.CharField(choices=[('poisson', 'Poisson'), ('fruitsdermer', 'Fruits de Mer'), ('crustace', 'Crustacé')], max_length=50)),
                ('en_promotion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ajout', 'Ajout'), ('retrait-par-vente', 'Retrait par vente'), ('retrait-par-invendus', 'Retrait par invendus')], max_length=50)),
                ('quantite', models.IntegerField()),
                ('prix', models.FloatField()),
                ('date', models.DateField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
    ]
